name: Docker Image TQ CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dockerhub-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        id: dockerhub-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

  extract-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Extract metadata for Docker (latest)
        id: meta-latest
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/bringwhat
          tags: latest

    outputs:
      latest_labels: ${{ steps.meta-latest.outputs.labels }}

  build-and-push-dockerhub:
    runs-on: ubuntu-latest
    needs: extract-metadata
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push - Latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
#          tags: ${{ needs.extract-metadata.outputs.latest_tags }}
          tags: ${{ secrets.DOCKER_USERNAME }}/bringwhat:latest
          labels: ${{ needs.extract-metadata.outputs.latest_labels }}

